spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:neondb}
    username: ${POSTGRES_USER:neondb_owner}
    password: ${POSTGRES_PASSWORD:npg_eVXG4qfL1FzP}
  jpa:
    hibernate:
      ddl-auto: validate       # to match your main config
    show-sql: true
  flyway:
    enabled: true
    # (add schemas: users here if you need it)
