services:
  postgres:
    image: postgres:16
    container_name: fintrack-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fintrack
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [fintrack-network]

  redis:
    image: redis:7
    container_name: fintrack-redis
    ports: ["6379:6379"]
    networks: [fintrack-network]

  # Kafka in KRaft mode (NO ZooKeeper)
  kafka:
    image: bitnami/kafka:latest
    container_name: fintrack-kafka
    ports: ["9092:9092", "29092:29092"]
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    networks: [fintrack-network]

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: fintrack-kafdrop
    depends_on: [kafka]
    ports: ["19000:9000"]
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    networks: [fintrack-network]

networks:
  fintrack-network:
    driver: bridge

volumes:
  pgdata:
  kafka_data:
