spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/fintrack_test}
    username: ${SPRING_DATASOURCE_USERNAME:test_user}
    password: ${SPRING_DATASOURCE_PASSWORD:test_pass}
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

