spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:fintrack}
    username: ${POSTGRES_USER:fintrack_user}
    password: ${POSTGRES_PASSWORD:fintrack_pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: false
