spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/fintrack_test}
    username: ${SPRING_DATASOURCE_USERNAME:test_user}
    password: ${SPRING_DATASOURCE_PASSWORD:test_pass}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  flyway:
    enabled: false
  redis:
    host: ${SPRING_REDIS_host: postgres}
    port: ${SPRING_REDIS_PORT:6379}

logging:
  level:
    org.springframework: WARN
    com.fintrack: INFO

