global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'reports-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reports-service:8084']

  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
        - 'host.docker.internal:8080'
        - 'host.docker.internal:8081'
        - 'host.docker.internal:8082'
        - 'host.docker.internal:8083'