apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-service
  namespace: fintrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports-service
  template:
    metadata:
      labels:
        app: reports-service
    spec:
      containers:
      - name: reports-service
        image: fintrack-reports-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "development"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/fintrack"
        - name: SPRING_DATASOURCE_USERNAME
          value: "fintrack_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "fintrack_pass"
---
apiVersion: v1
kind: Service
metadata:
  name: reports-service
  namespace: fintrack
spec:
  type: NodePort
  selector:
    app: reports-service
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30084
